version: '3'

services:
  postgres:
    image: postgres:15
    container_name: jobtracker
    environment:
      - POSTGRES_DB=jobtracker
      - POSTGRES_USER=jobtracker 
      - POSTGRES_PASSWORD=jobtracker123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres_sql/data 
    
volumes:
  postgres_data:
